services:
  - type: web
    name: jogae-sports-backend
    runtime: node
    plan: free
    rootDir: apps/backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_VERSION
        value: 20.18.0
